# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(961, 614)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 960, 600))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabBar::tab{width:320;height:50}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.tab_query = QtWidgets.QWidget(self.tab1)
        self.tab_query.setGeometry(QtCore.QRect(0, 0, 954, 545))
        self.tab_query.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tab_query.setObjectName("tab_query")
        self.widget_query = QtWidgets.QWidget(self.tab_query)
        self.widget_query.setGeometry(QtCore.QRect(0, 0, 960, 51))
        self.widget_query.setStyleSheet(".QWidget{background-color:rgb(212,212,212)}")
        self.widget_query.setObjectName("widget_query")
        self.textEdit = QtWidgets.QTextEdit(self.widget_query)
        self.textEdit.setGeometry(QtCore.QRect(150, 10, 104, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget_query)
        self.textEdit_2.setGeometry(QtCore.QRect(395, 10, 104, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.widget_query)
        self.textEdit_3.setGeometry(QtCore.QRect(660, 10, 104, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.widget_query)
        self.pushButton.setGeometry(QtCore.QRect(820, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setAutoRepeatInterval(99)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.widget_query)
        self.label.setGeometry(QtCore.QRect(55, 13, 91, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_query)
        self.label_2.setGeometry(QtCore.QRect(300, 13, 91, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_query)
        self.label_3.setGeometry(QtCore.QRect(545, 13, 111, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.widget_checkbox = QtWidgets.QWidget(self.tab_query)
        self.widget_checkbox.setGeometry(QtCore.QRect(0, 50, 960, 35))
        self.widget_checkbox.setStyleSheet(".QWidget{background-color:rgb(212,212,212)}")
        self.widget_checkbox.setObjectName("widget_checkbox")
        self.checkBox_G = QtWidgets.QCheckBox(self.widget_checkbox)
        self.checkBox_G.setGeometry(QtCore.QRect(100, 9, 81, 17))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.checkBox_G.setFont(font)
        self.checkBox_G.setObjectName("checkBox_G")
        self.checkBox_D = QtWidgets.QCheckBox(self.widget_checkbox)
        self.checkBox_D.setGeometry(QtCore.QRect(258, 9, 81, 17))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.checkBox_D.setFont(font)
        self.checkBox_D.setObjectName("checkBox_D")
        self.checkBox_Z = QtWidgets.QCheckBox(self.widget_checkbox)
        self.checkBox_Z.setGeometry(QtCore.QRect(415, 9, 81, 17))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.checkBox_Z.setFont(font)
        self.checkBox_Z.setObjectName("checkBox_Z")
        self.checkBox_T = QtWidgets.QCheckBox(self.widget_checkbox)
        self.checkBox_T.setGeometry(QtCore.QRect(572, 9, 81, 17))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.checkBox_T.setFont(font)
        self.checkBox_T.setObjectName("checkBox_T")
        self.checkBox_K = QtWidgets.QCheckBox(self.widget_checkbox)
        self.checkBox_K.setGeometry(QtCore.QRect(730, 9, 81, 17))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.checkBox_K.setFont(font)
        self.checkBox_K.setObjectName("checkBox_K")
        self.label_train_img = QtWidgets.QLabel(self.tab_query)
        self.label_train_img.setGeometry(QtCore.QRect(0, 80, 960, 62))
        self.label_train_img.setText("")
        self.label_train_img.setPixmap(QtGui.QPixmap(":/png/table_img.png"))
        self.label_train_img.setObjectName("label_train_img")
        self.tableView = QtWidgets.QTableView(self.tab_query)
        self.tableView.setGeometry(QtCore.QRect(0, 142, 960, 401))
        self.tableView.setObjectName("tableView")
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.tab_query_2 = QtWidgets.QWidget(self.tab2)
        self.tab_query_2.setGeometry(QtCore.QRect(0, 0, 960, 545))
        self.tab_query_2.setObjectName("tab_query_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_query_2)
        self.scrollArea.setGeometry(QtCore.QRect(0, 290, 955, 255))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 953, 253))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tab_analysis = QtWidgets.QWidget(self.tab_query_2)
        self.tab_analysis.setGeometry(QtCore.QRect(0, 0, 954, 545))
        self.tab_analysis.setObjectName("tab_analysis")
        self.widget_query_2 = QtWidgets.QWidget(self.tab_analysis)
        self.widget_query_2.setGeometry(QtCore.QRect(0, 0, 960, 51))
        self.widget_query_2.setStyleSheet(".QWidget{background-color: rgb(245, 245, 245)}")
        self.widget_query_2.setObjectName("widget_query_2")
        self.textEdit_analyisi_from = QtWidgets.QTextEdit(self.widget_query_2)
        self.textEdit_analyisi_from.setGeometry(QtCore.QRect(130, 10, 104, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        self.textEdit_analyisi_from.setFont(font)
        self.textEdit_analyisi_from.setObjectName("textEdit_analyisi_from")
        self.textEdit_analyisi_from_to = QtWidgets.QTextEdit(self.widget_query_2)
        self.textEdit_analyisi_from_to.setGeometry(QtCore.QRect(350, 10, 104, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        self.textEdit_analyisi_from_to.setFont(font)
        self.textEdit_analyisi_from_to.setObjectName("textEdit_analyisi_from_to")
        self.pushButton_analysis_query = QtWidgets.QPushButton(self.widget_query_2)
        self.pushButton_analysis_query.setGeometry(QtCore.QRect(490, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.pushButton_analysis_query.setFont(font)
        self.pushButton_analysis_query.setObjectName("pushButton_analysis_query")
        self.label_4 = QtWidgets.QLabel(self.widget_query_2)
        self.label_4.setGeometry(QtCore.QRect(30, 13, 91, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget_query_2)
        self.label_5.setGeometry(QtCore.QRect(260, 13, 91, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget_query_2)
        self.label_6.setGeometry(QtCore.QRect(640, 13, 22, 22))
        self.label_6.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_query_2)
        self.label_7.setGeometry(QtCore.QRect(760, 13, 22, 22))
        self.label_7.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget_query_2)
        self.label_8.setGeometry(QtCore.QRect(850, 13, 22, 22))
        self.label_8.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget_query_2)
        self.label_9.setGeometry(QtCore.QRect(670, 13, 72, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget_query_2)
        self.label_10.setGeometry(QtCore.QRect(790, 15, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.widget_query_2)
        self.label_11.setGeometry(QtCore.QRect(880, 13, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_analysis)
        self.tableWidget.setGeometry(QtCore.QRect(0, 50, 953, 241))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.tableWidget.setFont(font)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_analysis)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 290, 951, 241))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.tab_query_3 = QtWidgets.QWidget(self.tab3)
        self.tab_query_3.setGeometry(QtCore.QRect(0, 0, 954, 545))
        self.tab_query_3.setObjectName("tab_query_3")
        self.widget_time = QtWidgets.QWidget(self.tab_query_3)
        self.widget_time.setGeometry(QtCore.QRect(0, 0, 960, 551))
        self.widget_time.setStyleSheet(".QWidget#widget_time{background-image: url(:/png/time_bg.png)}")
        self.widget_time.setObjectName("widget_time")
        self.lineEdit_station = QtWidgets.QLineEdit(self.widget_time)
        self.lineEdit_station.setGeometry(QtCore.QRect(200, 150, 113, 30))
        self.lineEdit_station.setObjectName("lineEdit_station")
        self.pushButton_time_query = QtWidgets.QPushButton(self.widget_time)
        self.pushButton_time_query.setGeometry(QtCore.QRect(350, 150, 75, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.pushButton_time_query.setFont(font)
        self.pushButton_time_query.setObjectName("pushButton_time_query")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.widget_time)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 200, 951, 361))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 949, 359))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 200, 949, 359))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.label_12 = QtWidgets.QLabel(self.widget_time)
        self.label_12.setGeometry(QtCore.QRect(80, 153, 111, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.tab3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 961, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "火车票分析助手"))
        self.pushButton.setText(_translate("MainWindow", "查询"))
        self.label.setText(_translate("MainWindow", "出发地："))
        self.label_2.setText(_translate("MainWindow", "目的地："))
        self.label_3.setText(_translate("MainWindow", "出发日期："))
        self.checkBox_G.setText(_translate("MainWindow", "G-高铁"))
        self.checkBox_D.setText(_translate("MainWindow", "D-动车"))
        self.checkBox_Z.setText(_translate("MainWindow", "Z-直达"))
        self.checkBox_T.setText(_translate("MainWindow", "T-特快"))
        self.checkBox_K.setText(_translate("MainWindow", "K-快速"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "车票查询"))
        self.textEdit_analyisi_from.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Agency FB\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_analysis_query.setText(_translate("MainWindow", "查询"))
        self.label_4.setText(_translate("MainWindow", "出发地："))
        self.label_5.setText(_translate("MainWindow", "目的地："))
        self.label_9.setText(_translate("MainWindow", "非常紧张"))
        self.label_10.setText(_translate("MainWindow", "紧张"))
        self.label_11.setText(_translate("MainWindow", "不紧张"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "卧铺售票分析"))
        self.pushButton_time_query.setText(_translate("MainWindow", "查询"))
        self.label_12.setText(_translate("MainWindow", "起售车站："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "车票起售时间"))
# import img_rc
